add another bogus date

diff --git a/bin/cleantime b/bin/cleantime
--- a/bin/cleantime
+++ b/bin/cleantime
@@ -1,7 +1,7 @@
 #!/bin/sh
 #set -x
-ROOT=~/Downloads/tmpgoogle
-BOGUS_DATES='2007:10:06 2006:12:07 2006:12:11 2006:12:02'
+ROOT=/Users/fultonm/Documents/Development/googlepics/albums
+BOGUS_DATES='2007:10:06 2006:12:07 2006:12:11 2006:12:02 2006:12:14'
 for d in "${ROOT}/"*; do
 	echo "Process directory: ${d}"
 	bogusfiles=""
@@ -31,7 +31,7 @@ for d in "${ROOT}/"*; do
 		else 
 			touch -t "${touchdate}${touchtime}" "${f}" 
 			if [ $? -gt 0 ]; then
-				echo "Unable to touch file ${f} with date/time: ${touchdate}${touchtime}"
+				echo "Unable to touch file ${f} with date/time: ${touchdate}${touchtime}" >&2
 				exit 8
 			fi
 			lastdatetime="${datetime}"
@@ -41,7 +41,7 @@ for d in "${ROOT}/"*; do
 		fi
 	done
 	if ${allbogus} ; then
-		echo "All files in ${d} have bogus dates. Setting to January 1st 2020"
+		echo "All files in ${d} have bogus dates. Setting to January 1st 2020" >&2
 		touch -t "202001010101.01" "${d}"/*
 		exiftool -overwrite_original -DateTimeOriginal='2020:01:01 01:01:01' "${d}"/*
 	else
